######################################################################
# Automatically generated by qmake (2.01a) Sa. Sep 12 23:10:21 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rangedelegate.h rangeselector.h rangeselector_p.h
SOURCES += main.cpp rangedelegate.cpp rangeselector.cpp
