######################################################################
# Automatically generated by qmake (2.01a) So. Okt 11 00:31:38 2009
######################################################################

TEMPLATE = app
TARGET = modellistmodeltest
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += modellistmodel.h testing.h
SOURCES += modellistmodel.cpp testing.cpp
